In [1]:
import pandas as pd

In [7]:
train = pd.read_csv("train.csv")
train.head()

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [5]:
test = pd.read_csv("test.csv")
test.head()

        id        date  store_nbr      family  onpromotion
0  3000888  2017-08-16          1  AUTOMOTIVE            0
1  3000889  2017-08-16          1   BABY CARE            0
2  3000890  2017-08-16          1      BEAUTY            2
3  3000891  2017-08-16          1   BEVERAGES           20
4  3000892  2017-08-16          1       BOOKS            0

In [12]:
train_time = pd.to_datetime(train["date"])
test_time = pd.to_datetime(test["date"])

In [25]:
train_time.value_counts()

date
2017-08-15    1782
2013-01-01    1782
2013-01-02    1782
2013-01-03    1782
2017-07-30    1782
              ...
2013-01-09    1782
2013-01-08    1782
2013-01-07    1782
2013-01-06    1782
2013-01-05    1782
Name: count, Length: 1684, dtype: int64